### ISSUE TITLE
Una actividad puede tener 2 ó mas secuencias de aprobación y/o rechazo

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#2]
Una Actividad puede tener 2 ó mas secuencias de aprobación y/o de rechazo, lo cual causa incongruencia en el flujo de publicación 

Pasos para replicar la incidencia

1.- Se cuenta con un flujo de publicación creado
2.- Se cuenta con 3 actividades creadas en el flujo de publicación

Flujo

1.- Estando en el flujo de publicación seleccionar el botón agregar secuencia
2.- Agregar una secuencia de la actividad uno a la actividad 2 y así sucesivamente con las siguientes actividades 
3.- Agregar nuevamente una secuencia de aprobación en la actividad 1 y 2 y 3.

Resultado

Se permite crear secuencias de una actividad  sin que se valide como incorrecto.

**Comment by jordivs** [comment]
Se cumple con la validación de no repetir una secuencia en a misma actividad, pero al querer editar la secuencia existente, cambiando alguna configuración y guardar el cambio, realiza la validación como si se estuviera creando una nueva sin permitir editarla, enviando la ventana modal con la leyenda "La secuencia ya existe"

**Comment by haxdai** [comment]
Closed as duplicate of #3
