### ISSUE TITLE
Una actividad de rechazo puede ser secuenciada a terminar el flujo y publicar en automatico

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#3]
Una actividad de rechazo, puede ser secuenciada a terminar el flujo y publicar en automático y no se muestra la ventana de rechazo como en la versión de applet de flujos de publicación.

**Comment by haxdai** [comment]
Fixed by https://github.com/SemanticWebBuilder/SWB/commit/20b1ac1254375fea2e714e36aedfbffb451df3d7
