### ISSUE TITLE
Editor lento con archivos grandes

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWBPortal#73]
|Branch|
|---|
|no-applets|

La edición de plantillas con archivos grandes es muy lenta. El editor se cuelga en algunos casos, parece que es algo conocido de CodeMirror.

**Comment by jordivs** [comment]
@haxdai ,Se puede cerrar este issue, ya que cambiaste el editor?

**Comment by haxdai** [comment]
Si
