### ISSUE TITLE
Al tener 2 ediciones de platillas se borran los datos

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#76]
Al tener 2 plantillas con el editor abierto y en una de ellas se realizan modificaciones y se cambia a la 2da plantilla se pierde lo que ya se había realizado, aun cuando se haya guardado los cambios.

**Comment by haxdai** [comment]
@jordivs Algún error en la consola de Javascript? Versión particular de navegador?

**Comment by jordivs** [comment]
El bug se presenta solamente al tener 2 plantillas abiertas y se copia de una plantilla a otra y se guarda, la plantilla que se guardo al recargarla o cerrarla y volverla a abrir esta platilla tomará o duplicará lo que trae la platilla  que se copio el codigo. La consola del tomcat no presenta ningun error ni la consola de Javascript
y solamente sucede en el navegador de Firefox 52.0

**Comment by haxdai** [comment]
@jordivs puedes probar el fix?

**Comment by jordivs** [comment]
Se valida el funcionamiento correcto, las plantillas ya no se duplican al tener 2 en la edición.
