### ISSUE TITLE
Editor de template no se muestra en InternetExplorer

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#77]
Se realizó pruebas con IE Edge, 10, 9 y 8
La instancia tiene las siguientes caracteristicas:
Sistema Operativo: CentOS 7
Base de Datos: Hipersonic
Servidor de Aplicaciones: Tomcat-9.0.0M17

![2017-03-16_130006](https://cloud.githubusercontent.com/assets/7914633/24014326/21e3c32c-0a4a-11e7-9a0a-c78a371d6f2d.jpg)

La consola del Tomcat no genera ningun error,  pero la consola de firebug genera lo siguiente: 

![2017-03-16_130938](https://cloud.githubusercontent.com/assets/7914633/24014216/af018f74-0a49-11e7-8cec-b9e8613e5c1b.jpg)

**Comment by haxdai** [comment]
@jordivs no uses IE en CentOS 😝

IE menor que 11 no es soportado.

### Edge Windows 10 x64, Edge 38.14393.0.0, EdgeHTML 14.14393
![edge](https://cloud.githubusercontent.com/assets/7064389/24018460/8cfc6614-0a59-11e7-8b7f-a3f9d92373b4.png)

Reviso el caso de IE 11 para ver si se puede hacer algo.

**Comment by haxdai** [comment]
@jordivs regresé a código JS sin features de ES6 para que funcione en IE11 o menor, no estoy seguro de que funcione en todas las versiones de IE. Ver https://github.com/SemanticWebBuilder/SWBPortal/issues/78.

![ie11](https://cloud.githubusercontent.com/assets/7064389/24020786/5a099880-0a63-11e7-948a-a458ef615adf.png)


Hay otros componentes que usan javascript con features de ES6, habría que probar todos en IE si queremos soportarlos también.
