### ISSUE TITLE
Codificación de recursos

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWBPortal#82]
¿La codificación utilizada en todos los recursos debería ser ya UTF-8?

**Comment by jordivs** [comment]
Si debe ser en UTF-8, vamos a revisarlo con @softjei y @jajs1975 para medir el esfuerzo y hacer un plan de trabajo.

**Comment by jordivs** [comment]
This issue was moved to SemanticWebBuilder/SWB#23
