### ISSUE TITLE
Implementación de UTF-8 encoding  para las Plantillas

### ISSUE THREAD

**Issue by jordivs** [SemanticWebBuilder/SWBPortal#83]
Implica que en las instancias de producción tengan que actualizar cada plantilla del sitio para actualizar los cambios. https://github.com/SemanticWebBuilder/SWBPortal/commit/34f886f4a1ba145c2a9d9f2f83557aa468da2e69
¿Proponen alguna solución? para que no sea complicado para los usuarios que cuenten con varias plantillas en sus instancias.

**Comment by haxdai** [comment]
@jordivs cómo te fue con las pruebas?

**Comment by jordivs** [comment]
This issue was moved to SemanticWebBuilder/SWB#24
