### ISSUE TITLE
Los issues deberían registrarse en otro repositorio

### ISSUE THREAD

**Issue by haxdai** [SemanticWebBuilder/SWBPortal#85]
Los issues deberían reportarse en el proyecto SWB, puesto que es el proyecto Web que incorpora todos los módulos en SWBPortal. En su defecto, tendría sentido también reportarlos en SWBBundle.

**Comment by jordivs** [comment]
Tienes razón, se tienen que reportar en SWB, ¿Se podrán mover los issues de proyecto?

**Comment by jordivs** [comment]
Realizado el movimiento de los issues al repositorio de SWB con la herramienta Issue Mover GitHub https://github-issue-mover.appspot.com/

**Comment by jordivs** [comment]
This issue was moved to SemanticWebBuilder/SWB#25
